name: Build and Archive Linux
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  linuxBuild:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 16
          graalvm-version: 21.1.0
          native-image: true
      - name: Build
        run: ./gradlew nativeImage
        env:
          MULTI_PACKAGES_TOKEN: ${{ secrets.MULTI_PACKAGES_TOKEN }}
          MULTI_PACKAGES_USER: ${{ secrets.MULTI_PACKAGES_USER }}
      - uses: actions/upload-artifact@v2
        with:
          name: apimap
          path: build/executable/apimap

